Products
choodoss/project-group-5 pull request #7
Opened 2022-12-24 18:05 UTC by eashkod

2022-12-25 13:03 UTC, choodoss requested changes
Робота супер. Але я не певен, що картинки напоїв мають бути у бекграунді, в бекграунді має знаходитись стилізація але не контентні зображення. Бажано додати їх в html, не через бефор. У всьому іншому жодних заперечень. Ще як варінт, виключно по бажанню, видалити марджини між li і задати на ul gap-row: здається 168px; А загалом краща робота, так тримати

2022-12-25 13:48 UTC, eashkod commented
Доброго дня!
"Зображення на картках товарів є декоративними, їх необхідно реалізувати
псевдо-елементами."
Це із завдання? Переробляти зображення?

вс, 25 дек. 2022 г., 15:03 Дмитрий Хоменко ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Робота супер. Але я не певен, що картинки напоїв мають бути у бекграунді,
> в бекграунді має знаходитись стилізація але не контентні зображення. Бажано
> додати їх в html, не через бефор. У всьому іншому жодних заперечень. Ще як
> варінт, виключно по бажанню, видалити марджини між li і задати на ul
> gap-row: здається 168px; А загалом краща робота, так тримати
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/choodoss/project-group-5/pull/7#pullrequestreview-1229743151>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3R3VDTMAA64BP7KG2ITFS3WPBA3BANCNFSM6AAAAAATIR3D2Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-26 10:47 UTC, choodoss requested changes
https://www.loom.com/share/27153b6fb08e4f86b91b0c18c000f576

2022-12-26 17:53 UTC, choodoss approved these changes

2022-12-27 12:15 UTC, choodoss approved these changes

2022-12-27 12:15 UTC, merged